name: ci

on:
  push:
    paths:
      - "package.json"
      - "tsconfig.json"
      - "src/**"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "package.json"
      - "tsconfig.json"
      - "src/**"
      - ".github/workflows/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: "20"
          cache: "npm"
      - run: npm ci
      - run: npm run typecheck
      - run: npm run build
      - run: npm test --if-present
